import os


EMA_ALPHA = 0.3
ETA_RANGE_K = 1.0
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")
TELEGRAM_BOT_USERNAME = os.environ.get("TELEGRAM_BOT_USERNAME", "")
TELEGRAM_WEBHOOK_SECRET = os.environ.get("TELEGRAM_WEBHOOK_SECRET", "")
TELEGRAM_LINK_CODE_TTL_SECONDS = 600
TELEGRAM_SOFT_THRESHOLD_SECONDS = 900
TELEGRAM_SOFT_INTERVAL_SECONDS = 45
